#pragma once
#include "../../UnheardEngine.h"

// a header that store graphic API function callback
#include "Runtime/Platform/PlatformVulkan.h"

// Vulkan callback functions, mainly for functions that are not a part of core Vulkan

#if WITH_EDITOR
inline PFN_vkCmdBeginDebugUtilsLabelEXT GBeginCmdDebugLabelCallback;
inline PFN_vkCmdEndDebugUtilsLabelEXT GEndCmdDebugLabelCallback;
inline PFN_vkSetDebugUtilsObjectNameEXT GSetDebugUtilsObjectNameEXT;
#endif

inline PFN_vkGetAccelerationStructureDeviceAddressKHR GVkGetAccelerationStructureDeviceAddressKHR;
inline PFN_vkGetAccelerationStructureBuildSizesKHR GVkGetAccelerationStructureBuildSizesKHR;
inline PFN_vkCreateAccelerationStructureKHR GVkCreateAccelerationStructureKHR;
inline PFN_vkCmdBuildAccelerationStructuresKHR GVkCmdBuildAccelerationStructuresKHR;
inline PFN_vkDestroyAccelerationStructureKHR GVkDestroyAccelerationStructureKHR;
inline PFN_vkCreateRayTracingPipelinesKHR GVkCreateRayTracingPipelinesKHR;
inline PFN_vkCmdTraceRaysKHR GVkCmdTraceRaysKHR;
inline PFN_vkGetRayTracingShaderGroupHandlesKHR GVkGetRayTracingShaderGroupHandlesKHR;
inline PFN_vkSetHdrMetadataEXT GVkSetHdrMetadataEXT;
inline PFN_vkCmdPushDescriptorSetKHR GVkCmdPushDescriptorSetKHR;
inline PFN_vkCmdBeginConditionalRenderingEXT GVkCmdBeginConditionalRenderingEXT;
inline PFN_vkCmdEndConditionalRenderingEXT GVkCmdEndConditionalRenderingEXT;
inline PFN_vkCmdDrawMeshTasksEXT GVkCmdDrawMeshTasksEXT;